services:
  - type: web
    name: mydreamgirlfriend-landing
    env: node
    buildCommand: npm run build
    startCommand: npm start

  - type: web
    name: mydreamgirlfriend-cms
    env: node
    rootDir: cms
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
