import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';

export const metadata = {
  title: 'Terms of Service & Policies | My Dream Girlfriend',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 pt-20 px-4 pb-16 max-w-3xl mx-auto w-full">
        <h1 className="text-3xl font-bold mb-2">Terms of Service &amp; Policies</h1>
        <p className="text-muted text-sm mb-10">
          Effective Date: March 5, 2026 &mdash; Last Updated: April 29, 2026
        </p>

        <div className="space-y-10 text-sm leading-relaxed text-gray-300">
          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Refund &amp; Cancellation Policy</h2>
            <p className="mb-3">
              Black Bear Digital LLC (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;), operating the MyDreamGirlfriend.ai platform (&ldquo;My Dream Girlfriend&rdquo;), offers subscription-based access to AI companion services. By purchasing a subscription, you agree to the following:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">All sales are final.</strong> Due to the digital nature of the service, all subscription purchases are non-refundable once processed. No partial or prorated refunds will be issued for unused portions of a billing cycle.
              </li>
              <li>
                <strong className="text-white">Cancellation.</strong> You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period&mdash;you will retain access to paid features until that date. No refund is issued upon cancellation.
              </li>
              <li>
                <strong className="text-white">Billing disputes.</strong> If you believe a charge was made in error, contact us at{' '}
                <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>{' '}
                within 7 days of the charge. We will review and respond within 48 hours.
              </li>
              <li>
                <strong className="text-white">Free tier.</strong> No payment information is required to use free-tier features. Free accounts may be subject to usage limits.
              </li>
            </ul>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Synthetic Content &amp; AI-Generated Media Disclaimer</h2>
            <p className="mb-3">
              All characters, images, voice audio, and text conversations on My Dream Girlfriend are generated by artificial intelligence. Specifically:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">No real persons.</strong> Every character profile, including names, appearances, personalities, and biographical details, is entirely fictional. No real person is depicted, referenced, or modeled.
              </li>
              <li>
                <strong className="text-white">AI-generated imagery.</strong> Profile photos, in-chat images, and any other visual content are produced by generative AI models. These images do not represent photographs of real individuals.
              </li>
              <li>
                <strong className="text-white">AI-generated text &amp; voice.</strong> All chat messages and voice notes are synthesized by large language models and text-to-speech systems. Responses are algorithmically generated and do not represent communications from a real human.
              </li>
              <li>
                <strong className="text-white">No relationship guarantee.</strong> The service is for entertainment purposes only. Interactions with AI characters do not constitute real relationships, and we make no representations regarding emotional outcomes.
              </li>
            </ul>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Deepfakes &amp; CSAM &mdash; Zero-Tolerance Policy</h2>
            <p className="mb-3">
              My Dream Girlfriend maintains an absolute zero-tolerance policy regarding:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Deepfake content.</strong> Users may not upload, request, or attempt to generate images or media that depict the likeness of any real person. Any attempt to create non-consensual synthetic media of a real individual will result in immediate account termination.
              </li>
              <li>
                <strong className="text-white">Child Sexual Abuse Material (CSAM).</strong> Any content that sexualizes, depicts, or suggests sexual content involving minors (real or fictional) is strictly prohibited. We employ automated detection systems and human review to identify and remove such content immediately.
              </li>
              <li>
                <strong className="text-white">Reporting.</strong> Suspected violations are reported to the National Center for Missing &amp; Exploited Children (NCMEC) and relevant law enforcement authorities.
              </li>
              <li>
                <strong className="text-white">Enforcement.</strong> Violations result in immediate and permanent account termination, forfeiture of any remaining subscription balance, and referral to law enforcement where applicable.
              </li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Age Verification &amp; Access Restriction</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Minimum age.</strong> You must be at least 18 years of age to create an account and use My Dream Girlfriend.
              </li>
              <li>
                <strong className="text-white">Self-certification.</strong> During registration, all users must affirmatively confirm they are 18 years or older. By checking the age verification box, you represent and warrant that you meet this requirement.
              </li>
              <li>
                <strong className="text-white">Underage access.</strong> If we determine or reasonably suspect that a user is under 18, their account will be immediately suspended and all associated data deleted.
              </li>
              <li>
                <strong className="text-white">Parental responsibility.</strong> We are not responsible for minors who misrepresent their age. Parents and guardians are encouraged to monitor their children&rsquo;s internet usage and use parental controls.
              </li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. User Conduct &amp; Content Moderation</h2>
            <p className="mb-3">By using My Dream Girlfriend, you agree to the following conduct standards:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Prohibited content.</strong> You may not use the service to generate, solicit, or distribute content that: promotes violence or self-harm; involves minors in any sexual context; constitutes harassment, hate speech, or discrimination; infringes on intellectual property rights; or violates any applicable law.
              </li>
              <li>
                <strong className="text-white">Automated moderation.</strong> We use automated systems to detect and flag content that violates our policies. Flagged content may be removed without prior notice.
              </li>
              <li>
                <strong className="text-white">Account actions.</strong> We reserve the right to warn, suspend, or permanently terminate accounts that violate these policies, at our sole discretion and without refund.
              </li>
              <li>
                <strong className="text-white">User reporting.</strong> If you encounter content or behavior that violates these terms, please contact us at{' '}
                <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>.
              </li>
            </ul>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Billing Descriptor &amp; Customer Support</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Billing descriptor.</strong> Charges will appear on your credit card or bank statement under the descriptor &ldquo;BlkBear&rdquo; or a similar variation.
              </li>
              <li>
                <strong className="text-white">Customer support.</strong> For billing inquiries, account issues, or general support, contact us at{' '}
                <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>.
                We aim to respond to all inquiries within 48 hours.
              </li>
              <li>
                <strong className="text-white">Payment processing.</strong> Payments are processed by our third-party payment processor. We do not store your full credit card information on our servers.
              </li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Governing Law &amp; Severability</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Governing law.</strong> These terms are governed by and construed in accordance with the laws of the State of Florida, USA, without regard to its conflict of law principles.
              </li>
              <li>
                <strong className="text-white">Dispute resolution.</strong> Any disputes arising from these terms or your use of the service shall be resolved in the courts located in the State of Florida, USA. You consent to the personal jurisdiction of such courts.
              </li>
              <li>
                <strong className="text-white">Severability.</strong> If any provision of these terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
              </li>
              <li>
                <strong className="text-white">Entire agreement.</strong> These terms, together with our Privacy Policy, constitute the entire agreement between you and Black Bear Digital LLC regarding your use of the My Dream Girlfriend service.
              </li>
            </ul>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Subscription Cancellation Policy</h2>
            <p className="mb-4">
              If you purchase a recurring membership or subscription through MyDreamGirlfriend.ai,
              you may cancel future rebilling at any time.
            </p>
            <p className="mb-3">To cancel:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>
                You can cancel your subscription directly at{' '}
                <a href="https://mydreamgf.cc" target="_blank" rel="noopener noreferrer" className="text-accent-purple hover:underline">mydreamgf.cc</a>, or
              </li>
              <li>
                You can contact us directly at{' '}
                <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>{' '}
                with the email address used on your account and your request to cancel future rebills, or
              </li>
              <li>
                You can contact CCBill&rsquo;s Consumer Support and request cancellation of your
                subscription at{' '}
                <a href="https://support.ccbill.com/" target="_blank" rel="noopener noreferrer" className="text-accent-purple hover:underline">support.ccbill.com</a>{' '}
                or by phone at{' '}
                <a href="tel:+18885969279" className="text-accent-purple hover:underline whitespace-nowrap">1-888-596-9279</a>.
              </li>
            </ul>
            <p>
              Cancellations stop future rebilling. Access typically remains active until the end of
              the already-paid billing period. We recommend submitting cancellation requests at
              least 24 hours before the next scheduled rebill.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Anti&ndash;Human Trafficking &amp; Exploitation Policy</h2>
            <p className="mb-4">
              MyDreamGirlfriend.ai has a zero-tolerance policy for any form of human trafficking,
              sex trafficking, sexual exploitation, or physical abuse. We are committed to ensuring
              that our service cannot be used to promote, facilitate, or profit from these
              activities, consistent with Mastercard&rsquo;s and Visa&rsquo;s standards for adult
              content merchants.
            </p>
            <p className="mb-4">
              Our service provides AI-generated, fictional chat experiences only. We do not host
              real-world performers, cam models, escorts, or third-party content creators, and we do
              not allow users to advertise or arrange in-person services.
            </p>

            <h3 className="text-base font-semibold text-white mb-2">Prohibited uses</h3>
            <p className="mb-3">Users may not use MyDreamGirlfriend.ai to:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>Recruit, advertise, or solicit any person for commercial sex or sexual services.</li>
              <li>Exploit or attempt to exploit minors or vulnerable persons in any way.</li>
              <li>Promote, glorify, or coordinate human trafficking, sex trafficking, or physical abuse.</li>
              <li>Share links, contact details, or instructions intended to facilitate any of the above.</li>
            </ul>

            <h3 className="text-base font-semibold text-white mt-6 mb-2">Monitoring and enforcement</h3>
            <p className="mb-3">
              We use a combination of technical safeguards, content rules, and manual review to
              prevent and detect abusive or exploitative behavior on our platform. Violations of
              this policy may result in:
            </p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>Immediate removal of offending content;</li>
              <li>Suspension or termination of user accounts; and/or</li>
              <li>Reporting of suspected illegal activity to payment partners and/or appropriate law enforcement authorities.</li>
            </ul>

            <h3 className="text-base font-semibold text-white mt-6 mb-2">Reporting concerns</h3>
            <p className="mb-3">
              If you believe any activity on MyDreamGirlfriend.ai may be connected to human
              trafficking, sex trafficking, or exploitation, please contact us immediately at{' '}
              <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>{' '}
              and provide as much detail as possible (timestamps, screenshots, URLs). We investigate
              all such reports as a priority.
            </p>
            <p>
              If you or someone you know may be a victim of human trafficking, we encourage you to
              contact local law enforcement or a recognized anti-trafficking hotline in your country.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. 18 U.S.C. &sect; 2257 Exemption Statement</h2>
            <p className="mb-3">
              MyDreamGirlfriend.ai provides AI-generated, fictional chat experiences. We do not
              produce, host, or distribute visual depictions of actual human beings engaged in
              actual or simulated sexually explicit conduct.
            </p>
            <p className="mb-3">
              All characters and scenarios appearing on MyDreamGirlfriend.ai are entirely fictional
              and generated by artificial intelligence. Any images or avatars that may appear on the
              site are AI-generated or otherwise computer-generated and do not depict real persons.
            </p>
            <p className="mb-3">
              Because there are no visual depictions of actual human performers,
              MyDreamGirlfriend.ai is exempt from the record-keeping and labeling requirements of{' '}
              <strong className="text-white">18 U.S.C. &sect; 2257</strong>,{' '}
              <strong className="text-white">&sect; 2257A</strong>, and{' '}
              <strong className="text-white">28 C.F.R. Part 75</strong>.
            </p>
            <p>
              If you have any questions about this statement, please contact us at{' '}
              <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>.
            </p>
          </section>

          {/* Contact */}
          <section className="border-t border-border pt-8">
            <h2 className="text-xl font-semibold text-white mb-3">Contact Us</h2>
            <p>
              If you have any questions about these policies, please contact us at{' '}
              <a href="mailto:support@email.mydreamgirlfriend.ai" className="text-accent-purple hover:underline">support@email.mydreamgirlfriend.ai</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
