import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';

export const metadata = {
  title: 'Terms of Service & Policies | My Dream Girlfriend',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      <main className="flex-1 pt-20 px-4 pb-16 max-w-3xl mx-auto w-full">
        <h1 className="text-3xl font-bold mb-2">Terms of Service &amp; Policies</h1>
        <p className="text-muted text-sm mb-10">
          Effective Date: March 5, 2026 &mdash; Last Updated: March 5, 2026
        </p>

        <div className="space-y-10 text-sm leading-relaxed text-gray-300">
          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Refund &amp; Cancellation Policy</h2>
            <p className="mb-3">
              Black Bear Leads Inc. (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;), operating the MyDreamGirlfriend.ai platform (&ldquo;My Dream Girlfriend&rdquo;), offers subscription-based access to AI companion services. By purchasing a subscription, you agree to the following:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">All sales are final.</strong> Due to the digital nature of the service, all subscription purchases are non-refundable once processed. No partial or prorated refunds will be issued for unused portions of a billing cycle.
              </li>
              <li>
                <strong className="text-white">Cancellation.</strong> You may cancel your subscription at any time through your account settings. Cancellation takes effect at the end of the current billing period&mdash;you will retain access to paid features until that date. No refund is issued upon cancellation.
              </li>
              <li>
                <strong className="text-white">Billing disputes.</strong> If you believe a charge was made in error, contact us at{' '}
                <a href="mailto:jordan@blackbearleads.com" className="text-accent-purple hover:underline">jordan@blackbearleads.com</a>{' '}
                within 7 days of the charge. We will review and respond within 48 hours.
              </li>
              <li>
                <strong className="text-white">Free tier.</strong> No payment information is required to use free-tier features. Free accounts may be subject to usage limits.
              </li>
            </ul>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Synthetic Content &amp; AI-Generated Media Disclaimer</h2>
            <p className="mb-3">
              All characters, images, voice audio, and text conversations on My Dream Girlfriend are generated by artificial intelligence. Specifically:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">No real persons.</strong> Every character profile, including names, appearances, personalities, and biographical details, is entirely fictional. No real person is depicted, referenced, or modeled.
              </li>
              <li>
                <strong className="text-white">AI-generated imagery.</strong> Profile photos, in-chat images, and any other visual content are produced by generative AI models. These images do not represent photographs of real individuals.
              </li>
              <li>
                <strong className="text-white">AI-generated text &amp; voice.</strong> All chat messages and voice notes are synthesized by large language models and text-to-speech systems. Responses are algorithmically generated and do not represent communications from a real human.
              </li>
              <li>
                <strong className="text-white">No relationship guarantee.</strong> The service is for entertainment purposes only. Interactions with AI characters do not constitute real relationships, and we make no representations regarding emotional outcomes.
              </li>
            </ul>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Deepfakes &amp; CSAM &mdash; Zero-Tolerance Policy</h2>
            <p className="mb-3">
              My Dream Girlfriend maintains an absolute zero-tolerance policy regarding:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Deepfake content.</strong> Users may not upload, request, or attempt to generate images or media that depict the likeness of any real person. Any attempt to create non-consensual synthetic media of a real individual will result in immediate account termination.
              </li>
              <li>
                <strong className="text-white">Child Sexual Abuse Material (CSAM).</strong> Any content that sexualizes, depicts, or suggests sexual content involving minors (real or fictional) is strictly prohibited. We employ automated detection systems and human review to identify and remove such content immediately.
              </li>
              <li>
                <strong className="text-white">Reporting.</strong> Suspected violations are reported to the National Center for Missing &amp; Exploited Children (NCMEC) and relevant law enforcement authorities.
              </li>
              <li>
                <strong className="text-white">Enforcement.</strong> Violations result in immediate and permanent account termination, forfeiture of any remaining subscription balance, and referral to law enforcement where applicable.
              </li>
            </ul>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Age Verification &amp; Access Restriction</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Minimum age.</strong> You must be at least 18 years of age to create an account and use My Dream Girlfriend.
              </li>
              <li>
                <strong className="text-white">Self-certification.</strong> During registration, all users must affirmatively confirm they are 18 years or older. By checking the age verification box, you represent and warrant that you meet this requirement.
              </li>
              <li>
                <strong className="text-white">Underage access.</strong> If we determine or reasonably suspect that a user is under 18, their account will be immediately suspended and all associated data deleted.
              </li>
              <li>
                <strong className="text-white">Parental responsibility.</strong> We are not responsible for minors who misrepresent their age. Parents and guardians are encouraged to monitor their children&rsquo;s internet usage and use parental controls.
              </li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. User Conduct &amp; Content Moderation</h2>
            <p className="mb-3">By using My Dream Girlfriend, you agree to the following conduct standards:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Prohibited content.</strong> You may not use the service to generate, solicit, or distribute content that: promotes violence or self-harm; involves minors in any sexual context; constitutes harassment, hate speech, or discrimination; infringes on intellectual property rights; or violates any applicable law.
              </li>
              <li>
                <strong className="text-white">Automated moderation.</strong> We use automated systems to detect and flag content that violates our policies. Flagged content may be removed without prior notice.
              </li>
              <li>
                <strong className="text-white">Account actions.</strong> We reserve the right to warn, suspend, or permanently terminate accounts that violate these policies, at our sole discretion and without refund.
              </li>
              <li>
                <strong className="text-white">User reporting.</strong> If you encounter content or behavior that violates these terms, please contact us at{' '}
                <a href="mailto:jordan@blackbearleads.com" className="text-accent-purple hover:underline">jordan@blackbearleads.com</a>.
              </li>
            </ul>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Billing Descriptor &amp; Customer Support</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Billing descriptor.</strong> Charges will appear on your credit card or bank statement under the descriptor &ldquo;BlkBear&rdquo; or a similar variation.
              </li>
              <li>
                <strong className="text-white">Customer support.</strong> For billing inquiries, account issues, or general support, contact us at{' '}
                <a href="mailto:jordan@blackbearleads.com" className="text-accent-purple hover:underline">jordan@blackbearleads.com</a>.
                We aim to respond to all inquiries within 48 hours.
              </li>
              <li>
                <strong className="text-white">Payment processing.</strong> Payments are processed by our third-party payment processor. We do not store your full credit card information on our servers.
              </li>
            </ul>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Governing Law &amp; Severability</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                <strong className="text-white">Governing law.</strong> These terms are governed by and construed in accordance with the laws of the State of Florida, USA, without regard to its conflict of law principles.
              </li>
              <li>
                <strong className="text-white">Dispute resolution.</strong> Any disputes arising from these terms or your use of the service shall be resolved in the courts located in the State of Florida, USA. You consent to the personal jurisdiction of such courts.
              </li>
              <li>
                <strong className="text-white">Severability.</strong> If any provision of these terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force and effect.
              </li>
              <li>
                <strong className="text-white">Entire agreement.</strong> These terms, together with our Privacy Policy, constitute the entire agreement between you and Black Bear Leads Inc. regarding your use of the My Dream Girlfriend service.
              </li>
            </ul>
          </section>

          {/* Contact */}
          <section className="border-t border-border pt-8">
            <h2 className="text-xl font-semibold text-white mb-3">Contact Us</h2>
            <p>
              If you have any questions about these policies, please contact us at{' '}
              <a href="mailto:jordan@blackbearleads.com" className="text-accent-purple hover:underline">jordan@blackbearleads.com</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
