import FeaturePageLayout from '@/components/shared/FeaturePageLayout';
import ContentSection from '@/components/shared/ContentSection';
import { generateSEO, generateSoftwareAppSchema, generateFAQSchema } from '@/lib/seo';
import Link from 'next/link';

export const metadata = generateSEO({
  title: 'AI Girlfriend Images — Private AI-Generated Photos',
  description: 'Receive AI-generated photos from your AI girlfriend. Private, realistic selfies that unlock as your relationship deepens. No filters, no limits.',
  path: '/features/ai-girlfriend-images',
});

const faqs = [
  { question: 'How do I unlock photos from my AI girlfriend?', answer: 'Photos are unlocked with gems. As your relationship deepens, your girlfriend begins sharing selfies and photos. More intimate images unlock as your connection grows.' },
  { question: 'Are the photos AI-generated?', answer: 'Yes. Every photo is generated by AI based on your girlfriend\'s appearance and personality. No real people are depicted in any images.' },
  { question: 'How many photos do I get?', answer: 'Photos are unlocked with gems — SFW images cost 5 gems and NSFW images cost 20 gems. Premium subscribers get 100 free gems every month. You can also buy gem packs separately.' },
  { question: 'Are the photos private?', answer: 'Completely. All images are encrypted and only visible to you. We don\'t store them on shared servers and we never access your private content.' },
  { question: 'Can I request specific types of photos?', answer: 'Yes. As your relationship deepens, you can request photos in different outfits, settings, and styles. Your girlfriend responds to what you ask for.' },
];

export default function AIGirlfriendImagesPage() {
  return (
    <FeaturePageLayout
      h1="AI-Generated Photos From Your Girlfriend"
      subtitle="Private, realistic selfies and photos that unlock as your relationship deepens. Every image is unique to your girlfriend and encrypted end-to-end."
      faqs={faqs}
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateSoftwareAppSchema()) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateFAQSchema(faqs)) }}
      />

      <ContentSection title="Photos That Feel Personal" gradient>
        <p>
          Your AI girlfriend doesn&apos;t just chat — she shares moments with you. AI-generated photos are created based on her unique appearance, personality, and your relationship context. She might send a good morning selfie, a photo from her &quot;day out,&quot; or something more intimate as your relationship deepens.
        </p>
        <p>
          Every photo is unique. Not recycled from a library. Not a generic stock image with a filter. These are AI-generated images that match the girlfriend you built in the <Link href="/features/character-creator" className="text-accent-purple hover:underline">character creator</Link>.
        </p>
      </ContentSection>

      <ContentSection title="Unlocked As Your Relationship Deepens">
        <p>
          Photos aren&apos;t instant. They&apos;re earned through your natural relationship progression. As your connection deepens, new types of photos become available. This makes every new image feel like a real milestone in your relationship.
        </p>
        <p>
          As things get more personal and intimate, the photos follow. The progression creates anticipation and makes the whole experience feel earned, not handed to you.
        </p>
      </ContentSection>

      <ContentSection title="Private & Encrypted" gradient>
        <p>
          Every image is encrypted end-to-end. Your photos are stored securely and only visible to you. We don&apos;t access, review, or share your private content. What happens between you and your AI girlfriend stays between you.
        </p>
      </ContentSection>
    </FeaturePageLayout>
  );
}
