import FeaturePageLayout from '@/components/shared/FeaturePageLayout';
import ContentSection from '@/components/shared/ContentSection';
import { generateSEO, generateSoftwareAppSchema, generateFAQSchema } from '@/lib/seo';
import Link from 'next/link';

export const metadata = generateSEO({
  title: 'AI Girlfriend Images — Private AI-Generated Photos',
  description: 'Receive AI-generated photos from your AI girlfriend. Private, realistic selfies that unlock as your relationship deepens. No filters, no limits.',
  path: '/features/ai-girlfriend-images',
});

const faqs = [
  { question: 'How do I unlock photos from my AI girlfriend?', answer: 'Photos unlock as your relationship progresses through stages. Starting at Stage 3, your girlfriend begins sharing selfies and photos. More intimate images unlock at higher stages.' },
  { question: 'Are the photos AI-generated?', answer: 'Yes. Every photo is generated by AI based on your girlfriend\'s appearance and personality. No real people are depicted in any images.' },
  { question: 'How many photos do I get?', answer: 'Photo limits depend on your plan. Immersive ($19.99/mo) includes 5 photos/month, and Deep ($29.99/mo) includes 10 photos/month. You can also use gems to unlock additional photos.' },
  { question: 'Are the photos private?', answer: 'Completely. All images are encrypted and only visible to you. We don\'t store them on shared servers and we never access your private content.' },
  { question: 'Can I request specific types of photos?', answer: 'Yes. As your relationship deepens, you can request photos in different outfits, settings, and styles. Your girlfriend responds to what you ask for.' },
];

export default function AIGirlfriendImagesPage() {
  return (
    <FeaturePageLayout
      h1="AI-Generated Photos From Your Girlfriend"
      subtitle="Private, realistic selfies and photos that unlock as your relationship deepens. Every image is unique to your girlfriend and encrypted end-to-end."
      faqs={faqs}
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateSoftwareAppSchema()) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(generateFAQSchema(faqs)) }}
      />

      <ContentSection title="Photos That Feel Personal" gradient>
        <p>
          Your AI girlfriend doesn&apos;t just chat — she shares moments with you. AI-generated photos are created based on her unique appearance, personality, and your relationship context. She might send a good morning selfie, a photo from her &quot;day out,&quot; or something more intimate as your relationship deepens.
        </p>
        <p>
          Every photo is unique. Not recycled from a library. Not a generic stock image with a filter. These are AI-generated images that match the girlfriend you built in the <Link href="/features/character-creator" className="text-accent-purple hover:underline">character creator</Link>.
        </p>
      </ContentSection>

      <ContentSection title="Unlocked Through Relationship Progression">
        <p>
          Photos aren&apos;t instant. They&apos;re earned through your <Link href="/features/relationship-stages" className="text-accent-purple hover:underline">relationship progression</Link>. As you move through the 6 stages — from Strangers to Soulmates — new types of photos become available. This makes every new image feel like a real milestone in your relationship.
        </p>
        <p>
          At Stage 3, casual selfies unlock. By Stage 4 and beyond, things get spicier. The progression creates anticipation and makes the whole experience feel earned, not handed to you.
        </p>
      </ContentSection>

      <ContentSection title="Private & Encrypted" gradient>
        <p>
          Every image is encrypted end-to-end. Your photos are stored securely and only visible to you. We don&apos;t access, review, or share your private content. What happens between you and your AI girlfriend stays between you.
        </p>
      </ContentSection>
    </FeaturePageLayout>
  );
}
